# Standards: 2.5
---
# local.yml playbook
- hosts: 127.0.0.1 localhost
  become: yes
  become_method: su
  remote_user: root
  become_user: root
  connection: local

  tasks:
  - include: roles/common/tasks/external-ip.yml
  - include: roles/common/tasks/update.yml
  - include: roles/common/tasks/upgrade.yml
  - include: roles/common/tasks/cleanup.yml
  - include: roles/common/tasks/deb.yml