---
- name: Install epel repository
  yum:
    name: epel-release
    state: latest

- name: Add necessary repository
  yum:
    name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
    state: present

- name: Install XRDP
  yum:
    name: xrdp
    state: latest

- name: Install TigerVNC
  yum:
    name: tigervnc
    state: latest

- name: Start xrdp
  service:
    name: xrdp
    state: started
    enabled: yes

- name: global xsession file
  become: yes
  copy:
    src: xsession
    dest: /etc/skel/.xsession

- name: restart xrdp service
  become: yes
  service:
    name: xrdp
    enabled: yes
    state: restarted

- name: upload xrdp.ini
  become: yes
  copy:
    src: xrdp.ini
    dest: /etc/xrdp/xrdp.ini

- name: upload xrdp_keyboard.ini
  become: yes
  copy:
    src: xrdp_keyboard.ini
    dest: /etc/xrdp/xrdp_keyboard.ini

- name: upload sesman.ini
  become: yes
  copy:
    src: sesman.ini
    dest: /etc/xrdp/sesman.ini

- name: upload allow-colord.pkla
  become: yes
  copy:
    src: allow-colord.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/allow-colord.pkla

