# Standards: 2.6
---
# Install xfce desktop
- name: install xfce desktop packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  become: yes
  with_items:
  - git
  - vim
  - xfce4
  - xfce4-goodies
  - ubuntu-restricted-extras
